backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "links"
    label: "Links"
    folder: "src/pages/links"
    slug: "links"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "links-page"}
      - {label: "Title", name: "title", widget: "string", default: "Insta Links"}
      - label: "Background Image"
        name: "image"
        widget: "image"
      - label: "Links"
        name: "links"
        widget: "list"
        fields:
          - {label: Name, name: name, widget: string, default: "Link Here"}
          - {label: "URL", name: "url", widget: "string", default: "#"}